pre-commit:
  commands:
    test:
      glob: "*.go"
      run: go test -count=1 ./...
    lint:
      glob: "*.go"
      run: golangci-lint run --fix ./...

skip_output:
  - meta
  - summary
  - empty_summary
  - execution
  - success
  - skips
